[WIP]mypageのビューの実装
ayukua/freemarket_sample36_b pull request #14
Opened 2019-04-07 03:12 UTC by hosidalt

#WHAT
mypageのビューを作成しました。

#WHY
userの個人ページが必要だったため。

#POINT
・tabの切替えとl-sideのページ選択中のタブの変化はJavaScriptで作成してます。
・l-sideの選択先は現在rootかmypageにしか繋がっていないです。
・一番大枠になるmainのl-container、l-sideは他のページにも使用する予定なので個別的な名前のmypageをつけていません。
・scssのhtml,bodyはあとで共通させる予定なのでネストさせていません。
・後で使用考えているため現在使用していないクラス、Idがあります。

2019-04-07 03:18 UTC, yuki-uchida requested changes

2019-04-07 03:18 UTC, yuki-uchida commented on app/assets/javascripts/mypage.js
> +// $(function(){
コメントアウトは消してください

2019-04-07 03:18 UTC, yuki-uchida commented on app/assets/stylesheets/mypages.scss
> +    .tab-content {
BEMに沿ったクラス名をつけてアンバサンドを活用した省略形で書きましょう

2019-04-07 03:18 UTC, yuki-uchida commented on app/assets/stylesheets/mypages.scss
> +    .mypage-nav__head {
この辺りも

2019-04-07 03:18 UTC, yuki-uchida commented on app/assets/stylesheets/mypages.scss
> +      .mypage-nav__list-item:hover{
この辺りも

2019-04-07 04:34 UTC, hosidalt commented on app/assets/stylesheets/mypages.scss
> +    .tab-content {
.tab-content→.mypage__tab-contentに変更しました。

2019-04-07 04:34 UTC, hosidalt commented on app/assets/stylesheets/mypages.scss
> +    .mypage-nav__head {
mypage-nav__head→side-nav__headに変更しました。

2019-04-07 04:34 UTC, hosidalt commented on app/assets/stylesheets/mypages.scss
> +      .mypage-nav__list-item:hover{
mypage-nav__list-item→side-nav__list-item

2019-04-07 04:34 UTC, hosidalt commented on app/assets/javascripts/mypage.js
> +// $(function(){
修正しました。

2019-04-07 04:34 UTC, hosidalt commented
# WHAT
mypageのクラス名の修正とアンバサンドの活用

# WHY
コードを規則的し、省略することによって他の人が読んでも理解しやすくするため

# POINT
l-sideのブロックは後ほど部分テンプレートにするのでクラス名からmypageを抜きnav-sideという名称にしました。

2019-04-07 04:48 UTC, yuki-uchida requested changes

2019-04-07 04:48 UTC, yuki-uchida commented on app/assets/stylesheets/_l-side.scss
> +  .mypage-nav__head {
アンバサンドを活用した省略系で記述しましょう
こちら参考に。
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-04-07 06:52 UTC, hosidalt commented
# WHAT
mypageのクラス名をBEM記法に乗っ取て修正、アバサンドを活用

# WHY
コードを規則的にし、アバサンドを活用してコードを短く読みやすくするため

※
moduleとMerge remote-tracking branch 'origin/master'はコンフリクトが発生しましてそれを修正するのにlocalに残っていたファイルをプルしないとだめっだたようなのでプルしました

2019-04-07 06:55 UTC, yuki-uchida requested changes

2019-04-07 06:55 UTC, yuki-uchida commented on app/assets/stylesheets/_l-side.scss
> +    .mypage-nav__list-item:hover{
この辺りもアンバサンド使えます

2019-04-07 06:55 UTC, yuki-uchida commented on app/assets/stylesheets/mypages.scss
> +      .side-bar__nav__list__item:hover{
この辺りも

2019-04-07 08:00 UTC, yuki-uchida commented
申し訳ありませんがご質問はなんでしょうか？

2019-04-07 08:10 UTC, hosidalt commented
# .side-bar__nav__list__itemもアバサンドで省力した方がいいという指摘のことで

.side-bar__nav__list__itemはliタグで閉じてしまっているせいかアバサンドが効かないのですが
この場合はliタグにクラスをつけた方がいいんでしょうか、それともliタグ自体をクラスに代えた方がいいんでしょうか。

すみません、指摘を頂い所にメンションを付けて返信したのですが届いてませんでしたか。

2019-04-07 08:16 UTC, yuki-uchida commented
ありがとうございます。申し訳ありません、指摘に関しては見つけられませんでした。


ご質問に関してですが、この場合、liタグにクラス名を付与するのが良いです。そしてSCSS側ではliタグではなくそのクラス名で記述しましょう

2019-04-07 13:03 UTC, hosidalt commented
質問の回答ありがとうございました。

# WHAT
liタグにクラスを付与
scssの該当する部分をクラス名に変更し、アバサンドを活用

# WHY
コードを規則的にし、アバサンドを活用してコードを短く読みやすくするため

2019-04-08 01:58 UTC, kuroko918 commented on app/assets/javascripts/mypage.js
> +$(function(){
1行目の`$(function() {`の中にこれ以降の記述は入れてあげてこれは消しましょう！

2019-04-08 01:58 UTC, kuroko918 commented on app/assets/javascripts/mypage.js
> +$(function(){
1行目の`$(function() {`の中にこれ以降の記述は入れてあげてこれは消しましょう！

2019-04-08 01:58 UTC, kuroko918 commented on app/views/mypages/index.html.haml
> +  %body
1-5行目の記述はapplication.htmlに記述してあるかと思いますので、削除しておきましょう！

2019-04-08 01:58 UTC, kuroko918 commented on app/views/mypages/profile.html.haml
> +  %body
こちらも同様に1-5行目は消しておきましょう！

2019-04-08 01:58 UTC, kuroko918 commented on app/views/mypages/profile.html.haml
> +          %
こちらは何でしょう？

2019-04-08 01:58 UTC, kuroko918 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
不要なコメントは消しておいてください。

2019-04-08 09:23 UTC, hosidalt commented
app/views/mypages/profile.html.hamlはレビュー待ちの間に制作していたものでプルしたつもりはなかったのですが間違えてしてしまっていたみたいです。今回は無視してください、すみません。

# WHAT
不要なタグやコメントを消しました

# WHY
不要なタグやコメントを消しコード画面を見やすくするため

2019-04-08 09:38 UTC, kuroko918 commented
LGTMです！

2019-04-08 09:45 UTC, hosidalt commented
ありがとうございます(^^)

2019-04-14 02:09 UTC, merged