ユーザー新規登録、ログイン
ayukua/freemarket_sample36_b pull request #21
Opened 2019-04-14 06:01 UTC by ayukua

ハッシュタグ　aタグを修正しました

2019-04-14 06:04 UTC, yuki-uchida commented
コンフリクトが起きています

2019-04-14 06:06 UTC, yuki-uchida requested changes

2019-04-14 06:06 UTC, yuki-uchida commented on app/assets/stylesheets/signup.scss
> +.fa-envelope-o {
BEMに従ったクラス命名をつけ、様々な場所で使われるCSSはmixinで呼び出す形にしましょう
そうすることでSCSSファイルの構造がHTMLファイルの構造と同じ形になり、レイアウトが崩れたときにデバッグがしやすくなります

2019-04-20 00:59 UTC, ayukua commented on app/assets/stylesheets/signup.scss
> +.fa-envelope-o {
mixinや色を定義してメンテナンス性を向上させました。

2019-04-20 02:09 UTC, kuroko918 commented on app/assets/stylesheets/application.scss
> +@import"signup";
ここ三つですが、`@import`とファイル名の間にスペース1つ分開けておいてください！

2019-04-20 02:09 UTC, kuroko918 commented on app/views/devise/registrations/new.html.haml
> +  %body
1-7行目のことはapplication.htmlに記述してあることなので、削除しておいてください！

2019-04-20 02:20 UTC, miyagit commented on app/assets/stylesheets/signup.scss
> +    width: $width;
ここのインデント修正しましょう。

2019-04-20 02:20 UTC, miyagit commented on app/views/devise/registrations/new.html.haml
> +  %body
コチラどうなってますか？

2019-04-20 02:46 UTC, ayukua commented on app/assets/stylesheets/application.scss
> +@import"signup";
対応しました。

2019-04-20 02:46 UTC, ayukua commented on app/views/devise/registrations/new.html.haml
> +  %body
削除しました

2019-04-20 02:48 UTC, ayukua commented on app/views/devise/registrations/new.html.haml
> +  %body
削除しました

2019-04-20 02:48 UTC, ayukua commented on app/assets/stylesheets/signup.scss
> +    width: $width;
修正かけました

2019-04-20 02:50 UTC, miyagit commented on app/assets/stylesheets/signup.scss
> +    width: $width;
修正されていないのでpushのし忘れですかね？？

2019-04-20 02:59 UTC, ayukua commented on app/assets/stylesheets/signup.scss
> +    width: $width;
これは6行目のインデントを削除するという意味ではないのですか？

2019-04-20 03:03 UTC, miyagit commented on app/assets/stylesheets/signup.scss
> +    width: $width;
他の部分も全てそうですが、インデントがスペース４つになってるので、４つになってるものはすべて２つに修正してください。という意味です。

2019-04-20 03:10 UTC, ayukua commented on app/assets/stylesheets/signup.scss
> +    width: $width;
インデントの修正はかけましたが改行を行うと必ずインデント４つ作成させれてしまいます。
２つに変更する方法はありますか？

2019-04-20 03:12 UTC, miyagit approved these changes
LGTMです。

2019-04-20 06:56 UTC, merged